/**
 * Dockerfile generation for various project types
 * Generates optimized Docker images with x402 payment wrapper
 */

import { X402Config, ProjectType } from "../types/config.js";

/**
 * Base images for different project types
 */
const BASE_IMAGES: Record<ProjectType, string> = {
  "mcp-server": "node:20-alpine",
  "express-api": "node:20-alpine",
  "hono-api": "node:20-alpine",
  "fastapi": "python:3.11-slim",
  "nextjs": "node:20-alpine",
  "unknown": "node:20-alpine",
};

/**
 * Generate a Dockerfile based on project type
 */
export function generateDockerfile(
  config: X402Config,
  projectType: ProjectType
): string {
  switch (projectType) {
    case "fastapi":
      return generatePythonDockerfile(config);
    case "nextjs":
      return generateNextjsDockerfile(config);
    case "mcp-server":
    case "express-api":
    case "hono-api":
      return generateNodeDockerfile(config, projectType);
    default:
      return generateNodeDockerfile(config, projectType);
  }
}

/**
 * Generate Dockerfile for Node.js projects
 */
export function generateNodeDockerfile(
  config: X402Config,
  projectType: ProjectType = "unknown"
): string {
  const baseImage = BASE_IMAGES[projectType] || "node:20-alpine";
  const appName = config.name.replace(/[^a-z0-9-]/gi, "-").toLowerCase();

  return `# Auto-generated by x402-deploy
# Project: ${config.name} (${projectType})
# Version: ${config.version}

# ==================== Build Stage ====================
FROM ${baseImage} AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files
COPY package*.json ./
COPY pnpm-lock.yaml* ./
COPY yarn.lock* ./

# Install all dependencies (including dev for build)
RUN if [ -f pnpm-lock.yaml ]; then \\
      npm install -g pnpm && pnpm install --frozen-lockfile; \\
    elif [ -f yarn.lock ]; then \\
      yarn install --frozen-lockfile; \\
    else \\
      npm ci; \\
    fi

# Copy source code
COPY . .

# Build the application
RUN npm run build || echo "No build script found, skipping..."

# ==================== Production Stage ====================
FROM ${baseImage} AS production

LABEL org.opencontainers.image.title="${config.name}"
LABEL org.opencontainers.image.description="${config.description || "x402-enabled API"}"
LABEL org.opencontainers.image.vendor="x402-deploy"
LABEL x402.enabled="true"
LABEL x402.version="${config.version}"

WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S nodejs && \\
    adduser -S nodejs -u 1001

# Copy package files
COPY package*.json ./
COPY pnpm-lock.yaml* ./
COPY yarn.lock* ./

# Install production dependencies only
RUN if [ -f pnpm-lock.yaml ]; then \\
      npm install -g pnpm && pnpm install --frozen-lockfile --prod; \\
    elif [ -f yarn.lock ]; then \\
      yarn install --frozen-lockfile --production; \\
    else \\
      npm ci --only=production; \\
    fi

# Copy built application
COPY --from=builder /app/dist ./dist

# Copy x402 wrapper
COPY --from=builder /app/.x402 ./.x402

# Set ownership
RUN chown -R nodejs:nodejs /app

# Switch to non-root user
USER nodejs

# Environment variables
ENV NODE_ENV=production
ENV PORT=3000
ENV X402_ENABLED=true

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

EXPOSE 3000

# Start with x402 wrapper
CMD ["node", ".x402/wrapper.js"]
`;
}

/**
 * Generate Dockerfile for Python FastAPI projects
 */
export function generatePythonDockerfile(config: X402Config): string {
  return `# Auto-generated by x402-deploy
# Project: ${config.name} (fastapi)
# Version: ${config.version}

# ==================== Build Stage ====================
FROM python:3.11-slim AS builder

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    gcc \\
    python3-dev \\
    && rm -rf /var/lib/apt/lists/*

# Create virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy and install requirements
COPY requirements*.txt ./
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -r requirements.txt

# ==================== Production Stage ====================
FROM python:3.11-slim AS production

LABEL org.opencontainers.image.title="${config.name}"
LABEL org.opencontainers.image.description="${config.description || "x402-enabled FastAPI"}"
LABEL org.opencontainers.image.vendor="x402-deploy"
LABEL x402.enabled="true"
LABEL x402.version="${config.version}"

WORKDIR /app

# Create non-root user
RUN groupadd -g 1001 fastapi && \\
    useradd -r -u 1001 -g fastapi fastapi

# Copy virtual environment from builder
COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Copy application code
COPY . .

# Copy x402 wrapper
COPY .x402 ./.x402

# Set ownership
RUN chown -R fastapi:fastapi /app

# Switch to non-root user
USER fastapi

# Environment variables
ENV PYTHONUNBUFFERED=1
ENV PORT=3000
ENV X402_ENABLED=true

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:3000/health')" || exit 1

EXPOSE 3000

# Start with x402 wrapper
CMD ["python", ".x402/wrapper.py"]
`;
}

/**
 * Generate Dockerfile for Next.js projects
 */
export function generateNextjsDockerfile(config: X402Config): string {
  return `# Auto-generated by x402-deploy
# Project: ${config.name} (nextjs)
# Version: ${config.version}

# ==================== Dependencies Stage ====================
FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml* ./
COPY yarn.lock* ./

RUN if [ -f pnpm-lock.yaml ]; then \\
      npm install -g pnpm && pnpm install --frozen-lockfile; \\
    elif [ -f yarn.lock ]; then \\
      yarn install --frozen-lockfile; \\
    else \\
      npm ci; \\
    fi

# ==================== Build Stage ====================
FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ==================== Production Stage ====================
FROM node:20-alpine AS production

LABEL org.opencontainers.image.title="${config.name}"
LABEL org.opencontainers.image.description="${config.description || "x402-enabled Next.js"}"
LABEL org.opencontainers.image.vendor="x402-deploy"
LABEL x402.enabled="true"
LABEL x402.version="${config.version}"

WORKDIR /app

RUN addgroup -g 1001 -S nodejs && \\
    adduser -S nextjs -u 1001

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV X402_ENABLED=true

# Copy built assets
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.x402 ./.x402

RUN chown -R nextjs:nodejs /app

USER nextjs

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

EXPOSE 3000

CMD ["node", ".x402/wrapper.js"]
`;
}

/**
 * Generate .dockerignore file
 */
export function generateDockerignore(): string {
  return `# Auto-generated by x402-deploy
# Dependencies
node_modules
.pnpm-store
__pycache__
.venv
venv
*.pyc

# Build outputs
.next
dist
build
out
coverage

# Development
.git
.gitignore
.env.local
.env.development
.env.test
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# IDE
.idea
.vscode
*.swp
*.swo

# Test
tests
test
__tests__
*.test.ts
*.test.js
*.spec.ts
*.spec.js
vitest.config.*
jest.config.*

# Documentation
docs
*.md
!README.md

# x402 temp files
.x402/temp
.x402/*.log
`;
}
