/**
 * Fly.io deployment configuration generation
 * Generates fly.toml configuration files
 */

import { X402Config, ProjectType } from "../types/config.js";

/**
 * Fly.io configuration interface
 */
export interface FlyConfig {
  app: string;
  primary_region: string;
  kill_signal: string;
  kill_timeout: string;
  processes: Array<{
    name: string;
    cmd: string[];
  }>;
  build?: {
    dockerfile?: string;
    build_target?: string;
    args?: Record<string, string>;
  };
  deploy?: {
    release_command?: string;
    strategy?: string;
  };
  env: Record<string, string>;
  services: Array<{
    internal_port: number;
    protocol: string;
    force_https: boolean;
    auto_stop_machines: boolean;
    auto_start_machines: boolean;
    min_machines_running: number;
    concurrency: {
      type: string;
      soft_limit: number;
      hard_limit: number;
    };
    http_options?: {
      h2_backend: boolean;
    };
    ports: Array<{
      handlers: string[];
      port: number;
      force_https?: boolean;
    }>;
    http_checks: Array<{
      interval: string;
      timeout: string;
      path: string;
      method: string;
      protocol: string;
      grace_period?: string;
    }>;
  }>;
  mounts?: Array<{
    source: string;
    destination: string;
  }>;
  metrics?: {
    port: number;
    path: string;
  };
}

/**
 * Fly.io regions
 */
export const FLY_REGIONS = {
  // North America
  "iad": "Ashburn, Virginia, USA",
  "ord": "Chicago, Illinois, USA",
  "lax": "Los Angeles, California, USA",
  "sjc": "San Jose, California, USA",
  "sea": "Seattle, Washington, USA",
  "yul": "Montreal, Canada",
  "yyz": "Toronto, Canada",

  // Europe
  "ams": "Amsterdam, Netherlands",
  "cdg": "Paris, France",
  "fra": "Frankfurt, Germany",
  "lhr": "London, United Kingdom",
  "mad": "Madrid, Spain",

  // Asia Pacific
  "nrt": "Tokyo, Japan",
  "sin": "Singapore",
  "hkg": "Hong Kong",
  "syd": "Sydney, Australia",

  // South America
  "gru": "São Paulo, Brazil",
  "scl": "Santiago, Chile",
} as const;

export type FlyRegion = keyof typeof FLY_REGIONS;

/**
 * Get nearest Fly region from config or default
 */
function getRegion(config: X402Config): string {
  if (config.deploy?.region) {
    // Check if it's a valid Fly region
    if (config.deploy.region in FLY_REGIONS) {
      return config.deploy.region;
    }
    // Try to map common region names
    const regionMap: Record<string, string> = {
      "us-east": "iad",
      "us-west": "sjc",
      "eu-west": "ams",
      "eu-central": "fra",
      "ap-northeast": "nrt",
      "ap-southeast": "sin",
    };
    if (config.deploy.region in regionMap) {
      return regionMap[config.deploy.region];
    }
  }
  return "iad"; // Default to Virginia
}

/**
 * Generate fly.toml configuration
 */
export function generateFlyToml(config: X402Config): string {
  const appName = config.name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .substring(0, 63);

  const region = getRegion(config);
  const scaling = config.deploy?.scaling || { min: 1, max: 10 };
  const projectType = config.type || "unknown";

  const startCmd = projectType === "fastapi"
    ? "python .x402/wrapper.py"
    : "node .x402/wrapper.js";

  return `# Auto-generated by x402-deploy
# App: ${appName}
# Fly.io configuration

app = "${appName}"
primary_region = "${region}"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NODE_ENV = "production"

[deploy]
  strategy = "rolling"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  X402_ENABLED = "true"
  X402_WALLET = "${config.payment.wallet}"
  X402_NETWORK = "${config.payment.network}"
  X402_TOKEN = "${config.payment.token || "USDC"}"
  X402_PRICING_MODEL = "${config.pricing.model}"
  X402_DEFAULT_PRICE = "${config.pricing.default || "$0.001"}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = ${scaling.min === 0 ? '"stop"' : '"off"'}
  auto_start_machines = true
  min_machines_running = ${scaling.min}

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[checks]
  [checks.health]
    type = "http"
    port = 3000
    method = "GET"
    path = "/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Uncomment for persistent storage
# [[mounts]]
#   source = "data"
#   destination = "/app/data"

# Uncomment for metrics
# [metrics]
#   port = 9091
#   path = "/metrics"
`;
}

/**
 * Generate Fly secrets commands
 */
export function generateFlySecrets(config: X402Config): Record<string, string> {
  const secrets: Record<string, string> = {
    X402_ENABLED: "true",
    X402_WALLET: config.payment.wallet,
    X402_NETWORK: config.payment.network,
    X402_TOKEN: config.payment.token || "USDC",
    X402_PRICING_MODEL: config.pricing.model,
    X402_DEFAULT_PRICE: config.pricing.default || "$0.001",
  };

  if (config.payment.facilitator) {
    secrets.X402_FACILITATOR_URL = config.payment.facilitator;
  }

  // Route pricing travels as a single JSON blob
  if (config.pricing.routes && Object.keys(config.pricing.routes).length > 0) {
    secrets.X402_ROUTES = JSON.stringify(config.pricing.routes);
  }

  return secrets;
}

/**
 * Render the `fly secrets set` commands for a secret map, for docs and dry runs.
 */
export function generateFlySecretCommands(config: X402Config): string[] {
  return Object.entries(generateFlySecrets(config)).map(
    ([key, value]) => `fly secrets set ${key}=${JSON.stringify(value)}`
  );
}

/**
 * Generate Fly machines configuration for scaling
 */
export function generateFlyMachinesConfig(config: X402Config): string {
  const scaling = config.deploy?.scaling || { min: 1, max: 10 };

  return `# Fly machines configuration
# Auto-generated by x402-deploy

# Scale to ${scaling.min}-${scaling.max} machines
fly scale count ${scaling.min}

# Set auto-scaling
fly autoscale standard min=${scaling.min} max=${scaling.max}

# Configure machine size
fly scale vm shared-cpu-1x --memory 256

# List current status
fly status
`;
}

/**
 * Generate multi-region configuration
 */
export function generateFlyMultiRegion(
  config: X402Config,
  regions: FlyRegion[]
): string {
  const scaling = config.deploy?.scaling || { min: 1, max: 10 };
  const machinesPerRegion = Math.max(1, Math.floor(scaling.min / regions.length));

  let commands = `# Multi-region deployment for ${config.name}
# Auto-generated by x402-deploy

`;

  for (const region of regions) {
    commands += `# Deploy to ${FLY_REGIONS[region]}
fly scale count ${machinesPerRegion} --region ${region}

`;
  }

  commands += `# Verify deployment
fly status
fly regions list
`;

  return commands;
}
